install.packages("bayesplot")
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("cowplot")
install.packages("crayon")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("glue")
install.packages("knitr")
install.packages("loo")
install.packages("magrittr")
install.packages("parallel")
install.packages("purrr")
install.packages("QGglmm")
install.packages("random")
install.packages("readr")
install.packages("tidybayes")
install.packages("tidyr")
